[project]
authors = ["Cristian Acuña <c.acuna.sepulveda@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
description = "Add a short description here"
name = "Portfolio"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
pip = ">=24.3.1,<25"
scikit-learn = ">=1.6.1,<2"
keras = ">=3.8.0,<4"
polars = ">=1.20.0,<2"
jupyterlab = ">=4.3.4,<5"
tensorflow = ">=2.17.0,<3"
jupytext = ">=1.16.6,<2"
ruff = ">=0.9.2,<0.10"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2.3,<3"
bokeh = ">=3.6.2,<4"
ipywidgets = ">=8.1.5,<9"
ipympl = ">=0.9.6,<0.10"
